"""Pydantic schemas for the API responses."""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = Field(..., description="Overall health status")
    version: str = Field(..., description="API version")
    timestamp: datetime = Field(..., description="Server timestamp")


class ReadyResponse(BaseModel):
    """Readiness check response."""

    status: str = Field(..., description="Readiness status")
    delta_accessible: bool = Field(
        ..., description="Whether the Delta Lake is accessible"
    )


class SeriesInfo(BaseModel):
    """Information about a single series."""

    name: str = Field(..., description="Series name")
    description: str = Field(..., description="Human-readable description")
    frequency: str = Field(..., description="daily or monthly")
    unit: str = Field(..., description="Unit of measurement")


class SeriesListResponse(BaseModel):
    """Response for listing available series."""

    series: list[SeriesInfo] = Field(..., description="Available series")


class LatestValueResponse(BaseModel):
    """Response for the latest value of a series."""

    series: str = Field(..., description="Series name")
    year_month: str = Field(..., description="Year and month (YYYY-MM)")
    mean_value: float = Field(..., description="Average value for the month")
    min_value: float = Field(..., description="Minimum value in the month")
    max_value: float = Field(..., description="Maximum value in the month")
    observation_count: int = Field(
        ..., description="Number of observations in the month"
    )


class HistoryPoint(BaseModel):
    """A single point in the historical series."""

    year_month: str = Field(..., description="Year and month (YYYY-MM)")
    mean_value: float = Field(..., description="Average value")
    min_value: float = Field(..., description="Minimum value")
    max_value: float = Field(..., description="Maximum value")
    stddev_value: Optional[float] = Field(
        None, description="Standard deviation (null if only one observation)"
    )
    observation_count: int = Field(..., description="Number of observations")


class HistoryResponse(BaseModel):
    """Response for the history of a series."""

    series: str = Field(..., description="Series name")
    points: list[HistoryPoint] = Field(..., description="Historical data points")
    total_points: int = Field(..., description="Total number of points returned")


class SummaryResponse(BaseModel):
    """Response for the latest executive summary."""

    text: str = Field(..., description="Generated summary text")
    model: str = Field(..., description="Model used (gpt-4o-mini or fallback)")
    is_fallback: bool = Field(
        ..., description="True if the summary was generated by the fallback"
    )
    period_start: str = Field(..., description="Start of the period (YYYY-MM-DD)")
    period_end: str = Field(..., description="End of the period (YYYY-MM-DD)")
    generated_at: datetime = Field(..., description="When the summary was generated")
