"""Endpoint for the latest executive summary."""

from fastapi import APIRouter, HTTPException

from src.api_server.models.schemas import SummaryResponse
from src.api_server.services.delta_reader import get_latest_summary

router = APIRouter(tags=["summary"])


@router.get("/summary", response_model=SummaryResponse)
def summary() -> SummaryResponse:
    """Return the most recent executive summary generated by the pipeline."""
    row = get_latest_summary()
    if row is None:
        raise HTTPException(
            status_code=404,
            detail="No summary available. Run the pipeline first.",
        )

    return SummaryResponse(
        text=row["text"],
        model=row["model"],
        is_fallback=row["is_fallback"],
        period_start=row["period_start"],
        period_end=row["period_end"],
        generated_at=row["generated_at"],
    )
