#!/usr/bin/env bash
#
# Creates a Kind cluster for local development.
#
# The cluster is configured with an extraMount that maps the local
# spark-warehouse directory into the node, so the API pod can read
# the Delta Lake tables produced by the pipeline.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CLUSTER_NAME="jc-sre-local"
KIND_CONFIG="${PROJECT_ROOT}/kubernetes/kind/cluster-config.yaml"
SPARK_WAREHOUSE="${PROJECT_ROOT}/python/spark-warehouse"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Check prerequisites
check_prerequisites() {
    for cmd in docker kind kubectl; do
        if ! command -v "$cmd" &> /dev/null; then
            log_error "$cmd is not installed."
            exit 1
        fi
    done
    log_info "Prerequisites OK."
}

# Check that spark-warehouse exists and has data
check_spark_warehouse() {
    if [[ ! -d "${SPARK_WAREHOUSE}" ]]; then
        log_error "spark-warehouse not found at ${SPARK_WAREHOUSE}."
        log_error "Run 'make pipeline-run' first to populate it."
        exit 1
    fi

    if [[ ! -d "${SPARK_WAREHOUSE}/processed/monthly_aggregates" ]]; then
        log_warn "spark-warehouse exists but may not have processed data."
        log_warn "Consider running 'make pipeline-run' first."
    fi

    log_info "spark-warehouse found at ${SPARK_WAREHOUSE}."
}

# Check if cluster already exists
check_existing_cluster() {
    if kind get clusters 2>/dev/null | grep -q "^${CLUSTER_NAME}$"; then
        log_warn "Cluster '${CLUSTER_NAME}' already exists."
        read -p "Delete and recreate? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            log_info "Deleting existing cluster..."
            kind delete cluster --name "${CLUSTER_NAME}"
        else
            log_info "Keeping existing cluster. Exiting."
            exit 0
        fi
    fi
}

# Generate the Kind config with the absolute path for the extraMount
generate_kind_config() {
    log_info "Generating Kind configuration with extraMount..."

    cat > "${KIND_CONFIG}" <<EOF
# Kind cluster configuration for the JC SRE Databricks project.
#
# This file is generated by scripts/kind-setup.sh. It is not meant to be
# edited manually. The extraMount at the bottom maps the local
# spark-warehouse into the node, so the API pod can read Delta tables.
#
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ${CLUSTER_NAME}
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    extraMounts:
      - hostPath: ${SPARK_WAREHOUSE}
        containerPath: /data/spark-warehouse
        readOnly: true
EOF
}

# Create the cluster
create_cluster() {
    log_info "Creating Kind cluster '${CLUSTER_NAME}'..."
    kind create cluster --config "${KIND_CONFIG}"
    log_info "Cluster created."

    log_info "Waiting for the cluster to be ready..."
    kubectl wait --for=condition=Ready nodes --all --timeout=120s
    log_info "Cluster is ready."
}

# Install NGINX Ingress Controller
install_ingress() {
    log_info "Installing NGINX Ingress Controller..."

    if kubectl get namespace ingress-nginx &> /dev/null; then
        log_info "NGINX Ingress already installed."
        return
    fi

    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.3/deploy/static/provider/kind/deploy.yaml

    log_info "Waiting for NGINX Ingress Controller to be ready..."
    kubectl wait --namespace ingress-nginx \
        --for=condition=Ready pod \
        --selector=app.kubernetes.io/component=controller \
        --timeout=180s

    log_info "NGINX Ingress Controller ready."
}

# Print summary
print_summary() {
    echo
    log_info "======================================================"
    log_info "Kind cluster setup complete."
    log_info "======================================================"
    echo
    log_info "Cluster name: ${CLUSTER_NAME}"
    log_info "Spark warehouse mounted at: /data/spark-warehouse (inside the node)"
    echo
    log_info "Nodes:"
    kubectl get nodes
    echo
    log_info "Next steps:"
    log_info "  1. Build and load the API image:"
    log_info "     make kind-build"
    log_info "  2. Deploy the API:"
    log_info "     make kind-deploy"
    log_info "  3. Test the API at: http://jc-sre.local"
    echo
    log_warn "Add the following to /etc/hosts if not already present:"
    log_warn "  127.0.0.1  jc-sre.local"
    echo
}

main() {
    check_prerequisites
    check_spark_warehouse
    check_existing_cluster
    generate_kind_config
    create_cluster
    install_ingress
    print_summary
}

main "$@"