apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jc-sre-api.fullname" . }}
  labels:
    {{- include "jc-sre-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jc-sre-api.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "jc-sre-api.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "jc-sre-api.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: delta-warehouse
              mountPath: {{ .Values.persistence.mountPath }}
              readOnly: {{ .Values.persistence.readOnly }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: delta-warehouse
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: Directory
      {{- end }}
